version: "3.8"
services:
  keystone:
    build:
      context: .
    env_file:
      - path: envs/compose/keystone.env
    networks:
      - app-network
    ports:
      - "3000:3000"
networks:
  app-network: {}
