// -------------------------------------------------------------------------
// 🛑 THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
// -------------------------------------------------------------------------
// Run 'npm run generate:registry' (or build) to update.
    
export interface ComponentDef {
    id: string;
    label: string;
    files: string[];
    dependencies: string[];
    group: string; // 'default', 'keystone', 'textures'
}

export const GENERATED_COMPONENTS: ComponentDef[] = [
    {
        "id": ".bin",
        "label": ".bin",
        "files": [
            "components/node_modules/.bin"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@apollo",
        "label": "@apollo",
        "files": [
            "components/node_modules/@apollo"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@eslint",
        "label": "@eslint",
        "files": [
            "components/node_modules/@eslint"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@keystone-ui",
        "label": "@keystone-ui",
        "files": [
            "components/node_modules/@keystone-ui"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@md",
        "label": "@md",
        "files": [
            "components/node_modules/@md"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@types",
        "label": "@types",
        "files": [
            "components/node_modules/@types"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@typescript-eslint",
        "label": "@typescript-eslint",
        "files": [
            "components/node_modules/@typescript-eslint"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@uiw",
        "label": "@uiw",
        "files": [
            "components/node_modules/@uiw"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "Avatar",
        "label": "Avatar",
        "files": [
            "components/default/Avatar"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Badge",
        "label": "Badge",
        "files": [
            "components/default/Badge"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Breadcrumbs",
        "label": "Breadcrumbs",
        "files": [
            "components/default/Breadcrumbs"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Button",
        "label": "Button",
        "files": [
            "components/default/Button"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Buttons",
        "label": "Buttons",
        "files": [
            "components/default/Buttons"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Calendar",
        "label": "Calendar",
        "files": [
            "components/default/Calendar"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Card",
        "label": "Card",
        "files": [
            "components/default/Card"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Carousel",
        "label": "Carousel",
        "files": [
            "components/default/Carousel"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Charts",
        "label": "Charts (Recharts)",
        "files": [
            "components/default/Charts"
        ],
        "dependencies": [
            "recharts",
            "d3-scale"
        ],
        "group": "default"
    },
    {
        "id": "Cloud",
        "label": "Texture: Cloud",
        "files": [
            "components/textures/Cloud"
        ],
        "dependencies": [],
        "group": "textures"
    },
    {
        "id": "CodePreview",
        "label": "CodePreview",
        "files": [
            "components/default/CodePreview"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "ConditionalWrapper",
        "label": "ConditionalWrapper",
        "files": [
            "components/default/ConditionalWrapper"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Containers",
        "label": "Containers",
        "files": [
            "components/default/Containers"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "DateTimePicker",
        "label": "Keystone: DateTimePicker",
        "files": [
            "components/keystone/DateTimePicker"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "eslint",
        "label": "eslint",
        "files": [
            "components/node_modules/eslint"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-import",
        "label": "eslint-plugin-import",
        "files": [
            "components/node_modules/eslint-plugin-import"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-jsx-a11y",
        "label": "eslint-plugin-jsx-a11y",
        "files": [
            "components/node_modules/eslint-plugin-jsx-a11y"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-react",
        "label": "eslint-plugin-react",
        "files": [
            "components/node_modules/eslint-plugin-react"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-react-hooks",
        "label": "eslint-plugin-react-hooks",
        "files": [
            "components/node_modules/eslint-plugin-react-hooks"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "Form",
        "label": "Form",
        "files": [
            "components/default/Form"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Form",
        "label": "Keystone: Form",
        "files": [
            "components/keystone/Form"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "Header",
        "label": "Header",
        "files": [
            "components/default/Header"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "HtmlEditor",
        "label": "Rich Text Editor",
        "files": [
            "components/default/HtmlEditor"
        ],
        "dependencies": [
            "@tiptap/react",
            "@tiptap/starter-kit"
        ],
        "group": "default"
    },
    {
        "id": "Icons",
        "label": "Icons",
        "files": [
            "components/default/Icons"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Icons",
        "label": "Keystone: Icons",
        "files": [
            "components/keystone/Icons"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "Images",
        "label": "Images",
        "files": [
            "components/default/Images"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Label",
        "label": "Keystone: Label",
        "files": [
            "components/keystone/Label"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "Link",
        "label": "Link",
        "files": [
            "components/default/Link"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Loading",
        "label": "Loading Indicators",
        "files": [
            "components/default/Loading"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "LoadingSpinner",
        "label": "LoadingSpinner",
        "files": [
            "components/default/LoadingSpinner"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Logger",
        "label": "Logger",
        "files": [
            "components/default/Logger"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Logger",
        "label": "Keystone: Logger",
        "files": [
            "components/keystone/Logger"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "Logo",
        "label": "Logo",
        "files": [
            "components/default/Logo"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "lucide-react",
        "label": "lucide-react",
        "files": [
            "components/node_modules/lucide-react"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "MenuItem",
        "label": "MenuItem",
        "files": [
            "components/default/MenuItem"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Modals",
        "label": "Modals",
        "files": [
            "components/default/Modals"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Modals",
        "label": "Keystone: Modals",
        "files": [
            "components/keystone/Modals"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "moment",
        "label": "moment",
        "files": [
            "components/node_modules/moment"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "NavItem",
        "label": "Keystone: NavItem",
        "files": [
            "components/keystone/NavItem"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "next",
        "label": "next",
        "files": [
            "components/node_modules/next"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "next-image-export-optimizer",
        "label": "next-image-export-optimizer",
        "files": [
            "components/node_modules/next-image-export-optimizer"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "Pagination",
        "label": "Pagination",
        "files": [
            "components/default/Pagination"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "PaginationOld",
        "label": "PaginationOld",
        "files": [
            "components/default/PaginationOld"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Paper",
        "label": "Texture: Paper",
        "files": [
            "components/textures/Paper"
        ],
        "dependencies": [],
        "group": "textures"
    },
    {
        "id": "prettier",
        "label": "prettier",
        "files": [
            "components/node_modules/prettier"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "prism-themes",
        "label": "prism-themes",
        "files": [
            "components/node_modules/prism-themes"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "prismjs",
        "label": "prismjs",
        "files": [
            "components/node_modules/prismjs"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "ProgressBar",
        "label": "ProgressBar",
        "files": [
            "components/default/ProgressBar"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "react",
        "label": "react",
        "files": [
            "components/node_modules/react"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-color",
        "label": "react-color",
        "files": [
            "components/node_modules/react-color"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-dom",
        "label": "react-dom",
        "files": [
            "components/node_modules/react-dom"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-icons",
        "label": "react-icons",
        "files": [
            "components/node_modules/react-icons"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "recharts",
        "label": "recharts",
        "files": [
            "components/node_modules/recharts"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "Separator",
        "label": "Separator",
        "files": [
            "components/default/Separator"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Spinner",
        "label": "Spinner",
        "files": [
            "components/default/Spinner"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "StatusLabel",
        "label": "StatusLabel",
        "files": [
            "components/default/StatusLabel"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "styled-components",
        "label": "styled-components",
        "files": [
            "components/node_modules/styled-components"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "Switch",
        "label": "Switch",
        "files": [
            "components/default/Switch"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Table",
        "label": "Table",
        "files": [
            "components/default/Table"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Tabs",
        "label": "Tabs",
        "files": [
            "components/default/Tabs"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "TimestampValue",
        "label": "TimestampValue",
        "files": [
            "components/default/TimestampValue"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Toggle",
        "label": "Toggle",
        "files": [
            "components/default/Toggle"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Toggle",
        "label": "Keystone: Toggle",
        "files": [
            "components/keystone/Toggle"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "TokenInputField",
        "label": "TokenInputField",
        "files": [
            "components/default/TokenInputField"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Tooltip",
        "label": "Tooltip",
        "files": [
            "components/default/Tooltip"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "typescript",
        "label": "typescript",
        "files": [
            "components/node_modules/typescript"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "Typography",
        "label": "Typography",
        "files": [
            "components/default/Typography"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "Validation",
        "label": "Validation",
        "files": [
            "components/default/Validation"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "VerticalTabs",
        "label": "VerticalTabs",
        "files": [
            "components/default/VerticalTabs"
        ],
        "dependencies": [],
        "group": "default"
    }
];

export const GENERATED_SECTIONS: ComponentDef[] = [
    {
        "id": ".bin",
        "label": ".bin",
        "files": [
            "sections/node_modules/.bin"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@apollo",
        "label": "@apollo",
        "files": [
            "sections/node_modules/@apollo"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@eslint",
        "label": "@eslint",
        "files": [
            "sections/node_modules/@eslint"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@keystone-6",
        "label": "@keystone-6",
        "files": [
            "sections/node_modules/@keystone-6"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@keystone-ui",
        "label": "@keystone-ui",
        "files": [
            "sections/node_modules/@keystone-ui"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@md",
        "label": "@md",
        "files": [
            "sections/node_modules/@md"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@types",
        "label": "@types",
        "files": [
            "sections/node_modules/@types"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@typescript-eslint",
        "label": "@typescript-eslint",
        "files": [
            "sections/node_modules/@typescript-eslint"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "@uiw",
        "label": "@uiw",
        "files": [
            "sections/node_modules/@uiw"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "ActionButtons",
        "label": "Keystone: ActionButtons",
        "files": [
            "sections/keystone/ActionButtons"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "ButtonGroup",
        "label": "Keystone: ButtonGroup",
        "files": [
            "sections/keystone/ButtonGroup"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "ConditionalField",
        "label": "Keystone: ConditionalField",
        "files": [
            "sections/keystone/ConditionalField"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "CreateItemForm",
        "label": "Keystone: CreateItemForm",
        "files": [
            "sections/keystone/CreateItemForm"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "DynamicForms",
        "label": "Keystone: DynamicForms",
        "files": [
            "sections/keystone/DynamicForms"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "EditItemForm",
        "label": "Keystone: EditItemForm",
        "files": [
            "sections/keystone/EditItemForm"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "eslint",
        "label": "eslint",
        "files": [
            "sections/node_modules/eslint"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-import",
        "label": "eslint-plugin-import",
        "files": [
            "sections/node_modules/eslint-plugin-import"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-jsx-a11y",
        "label": "eslint-plugin-jsx-a11y",
        "files": [
            "sections/node_modules/eslint-plugin-jsx-a11y"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-react",
        "label": "eslint-plugin-react",
        "files": [
            "sections/node_modules/eslint-plugin-react"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "eslint-plugin-react-hooks",
        "label": "eslint-plugin-react-hooks",
        "files": [
            "sections/node_modules/eslint-plugin-react-hooks"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "fast-deep-equal",
        "label": "fast-deep-equal",
        "files": [
            "sections/node_modules/fast-deep-equal"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "HamburgerMenu",
        "label": "HamburgerMenu",
        "files": [
            "sections/default/HamburgerMenu"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "ItemsList",
        "label": "Keystone: ItemsList",
        "files": [
            "sections/keystone/ItemsList"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "Modals",
        "label": "Keystone: Modals",
        "files": [
            "sections/keystone/Modals"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "moment",
        "label": "moment",
        "files": [
            "sections/node_modules/moment"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "next",
        "label": "next",
        "files": [
            "sections/node_modules/next"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "next-image-export-optimizer",
        "label": "next-image-export-optimizer",
        "files": [
            "sections/node_modules/next-image-export-optimizer"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "NotFoundSection",
        "label": "NotFoundSection",
        "files": [
            "sections/default/NotFoundSection"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "NotFoundSection",
        "label": "Keystone: NotFoundSection",
        "files": [
            "sections/keystone/NotFoundSection"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "PageContainer",
        "label": "Keystone: PageContainer",
        "files": [
            "sections/keystone/PageContainer"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "prettier",
        "label": "prettier",
        "files": [
            "sections/node_modules/prettier"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react",
        "label": "react",
        "files": [
            "sections/node_modules/react"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-color",
        "label": "react-color",
        "files": [
            "sections/node_modules/react-color"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-dom",
        "label": "react-dom",
        "files": [
            "sections/node_modules/react-dom"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-dropzone",
        "label": "react-dropzone",
        "files": [
            "sections/node_modules/react-dropzone"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-icons",
        "label": "react-icons",
        "files": [
            "sections/node_modules/react-icons"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "react-timezone-select",
        "label": "react-timezone-select",
        "files": [
            "sections/node_modules/react-timezone-select"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "recharts",
        "label": "recharts",
        "files": [
            "sections/node_modules/recharts"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "SignInContainer",
        "label": "Keystone: SignInContainer",
        "files": [
            "sections/keystone/SignInContainer"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "styled-components",
        "label": "styled-components",
        "files": [
            "sections/node_modules/styled-components"
        ],
        "dependencies": [],
        "group": "node_modules"
    },
    {
        "id": "typescript",
        "label": "typescript",
        "files": [
            "sections/node_modules/typescript"
        ],
        "dependencies": [],
        "group": "node_modules"
    }
];
