// -------------------------------------------------------------------------
// 🛑 THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
// -------------------------------------------------------------------------
// Run 'npm run generate:registry' (or build) to update.
    
export interface ComponentDef {
    id: string;
    label: string;
    files: string[];
    dependencies: string[];
    group: string; // 'default', 'keystone', 'textures'
    category?: string; // e.g. 'forms', 'data-display'
}

export const GENERATED_COMPONENTS: ComponentDef[] = [
    {
        "id": "default-common-Icons",
        "label": "Icons",
        "files": [
            "components/default/common/Icons"
        ],
        "dependencies": [],
        "group": "default",
        "category": "common"
    },
    {
        "id": "default-common-Logo",
        "label": "Logo",
        "files": [
            "components/default/common/Logo"
        ],
        "dependencies": [],
        "group": "default",
        "category": "common"
    },
    {
        "id": "default-data-display-Avatar",
        "label": "Avatar",
        "files": [
            "components/default/data-display/Avatar"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Badge",
        "label": "Badge",
        "files": [
            "components/default/data-display/Badge"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Card",
        "label": "Card",
        "files": [
            "components/default/data-display/Card"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Carousel",
        "label": "Carousel",
        "files": [
            "components/default/data-display/Carousel"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-CodePreview",
        "label": "CodePreview",
        "files": [
            "components/default/data-display/CodePreview"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Images",
        "label": "Images",
        "files": [
            "components/default/data-display/Images"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-ProgressBar",
        "label": "ProgressBar",
        "files": [
            "components/default/data-display/ProgressBar"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-StatusLabel",
        "label": "StatusLabel",
        "files": [
            "components/default/data-display/StatusLabel"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Table",
        "label": "Table",
        "files": [
            "components/default/data-display/Table"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Tooltip",
        "label": "Tooltip",
        "files": [
            "components/default/data-display/Tooltip"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-data-display-Typography",
        "label": "Typography",
        "files": [
            "components/default/data-display/Typography"
        ],
        "dependencies": [],
        "group": "default",
        "category": "data-display"
    },
    {
        "id": "default-feedback-Loading",
        "label": "Loading Indicators",
        "files": [
            "components/default/feedback/Loading"
        ],
        "dependencies": [],
        "group": "default",
        "category": "feedback"
    },
    {
        "id": "default-feedback-Toasts",
        "label": "Toasts",
        "files": [
            "components/default/feedback/Toasts"
        ],
        "dependencies": [],
        "group": "default",
        "category": "feedback"
    },
    {
        "id": "default-feedback-Validation",
        "label": "Validation",
        "files": [
            "components/default/feedback/Validation"
        ],
        "dependencies": [],
        "group": "default",
        "category": "feedback"
    },
    {
        "id": "default-forms-Button",
        "label": "Button",
        "files": [
            "components/default/forms/Button"
        ],
        "dependencies": [],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-forms-Calendar",
        "label": "Calendar",
        "files": [
            "components/default/forms/Calendar"
        ],
        "dependencies": [],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-forms-Form",
        "label": "Form",
        "files": [
            "components/default/forms/Form"
        ],
        "dependencies": [],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-forms-HtmlEditor",
        "label": "Rich Text Editor",
        "files": [
            "components/default/forms/HtmlEditor"
        ],
        "dependencies": [
            "@tiptap/react",
            "@tiptap/starter-kit"
        ],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-forms-Switch",
        "label": "Switch",
        "files": [
            "components/default/forms/Switch"
        ],
        "dependencies": [],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-forms-Toggle",
        "label": "Toggle",
        "files": [
            "components/default/forms/Toggle"
        ],
        "dependencies": [],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-forms-TokenInputField",
        "label": "TokenInputField",
        "files": [
            "components/default/forms/TokenInputField"
        ],
        "dependencies": [],
        "group": "default",
        "category": "forms"
    },
    {
        "id": "default-layout-ConditionalWrapper",
        "label": "ConditionalWrapper",
        "files": [
            "components/default/layout/ConditionalWrapper"
        ],
        "dependencies": [],
        "group": "default",
        "category": "layout"
    },
    {
        "id": "default-layout-Containers",
        "label": "Containers",
        "files": [
            "components/default/layout/Containers"
        ],
        "dependencies": [],
        "group": "default",
        "category": "layout"
    },
    {
        "id": "default-layout-Separator",
        "label": "Separator",
        "files": [
            "components/default/layout/Separator"
        ],
        "dependencies": [],
        "group": "default",
        "category": "layout"
    },
    {
        "id": "default-navigation-Breadcrumbs",
        "label": "Breadcrumbs",
        "files": [
            "components/default/navigation/Breadcrumbs"
        ],
        "dependencies": [],
        "group": "default",
        "category": "navigation"
    },
    {
        "id": "default-navigation-Header",
        "label": "Header",
        "files": [
            "components/default/navigation/Header"
        ],
        "dependencies": [],
        "group": "default",
        "category": "navigation"
    },
    {
        "id": "default-navigation-Link",
        "label": "Link",
        "files": [
            "components/default/navigation/Link"
        ],
        "dependencies": [],
        "group": "default",
        "category": "navigation"
    },
    {
        "id": "default-navigation-Pagination",
        "label": "Pagination",
        "files": [
            "components/default/navigation/Pagination"
        ],
        "dependencies": [],
        "group": "default",
        "category": "navigation"
    },
    {
        "id": "default-navigation-Tabs",
        "label": "Tabs",
        "files": [
            "components/default/navigation/Tabs"
        ],
        "dependencies": [],
        "group": "default",
        "category": "navigation"
    },
    {
        "id": "default-overlays-Modals",
        "label": "Modals",
        "files": [
            "components/default/overlays/Modals"
        ],
        "dependencies": [],
        "group": "default",
        "category": "overlays"
    },
    {
        "id": "keystone-common-Icons",
        "label": "Icons",
        "files": [
            "components/keystone/common/Icons"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "common"
    },
    {
        "id": "keystone-data-display-Label",
        "label": "Label",
        "files": [
            "components/keystone/data-display/Label"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "data-display"
    },
    {
        "id": "keystone-feedback-Logger",
        "label": "Logger",
        "files": [
            "components/keystone/feedback/Logger"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "feedback"
    },
    {
        "id": "keystone-forms-DateTimePicker",
        "label": "DateTimePicker",
        "files": [
            "components/keystone/forms/DateTimePicker"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-Form",
        "label": "Form",
        "files": [
            "components/keystone/forms/Form"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-Toggle",
        "label": "Toggle",
        "files": [
            "components/keystone/forms/Toggle"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-navigation-NavItem",
        "label": "NavItem",
        "files": [
            "components/keystone/navigation/NavItem"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "navigation"
    },
    {
        "id": "keystone-overlays-Modals",
        "label": "Modals",
        "files": [
            "components/keystone/overlays/Modals"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "overlays"
    },
    {
        "id": "textures-Cloud",
        "label": "Cloud",
        "files": [
            "components/textures/Cloud"
        ],
        "dependencies": [],
        "group": "textures"
    },
    {
        "id": "textures-Paper",
        "label": "Paper",
        "files": [
            "components/textures/Paper"
        ],
        "dependencies": [],
        "group": "textures"
    }
];

export const GENERATED_SECTIONS: ComponentDef[] = [
    {
        "id": "default-feedback-NotFoundSection",
        "label": "NotFoundSection",
        "files": [
            "sections/default/feedback/NotFoundSection"
        ],
        "dependencies": [],
        "group": "default",
        "category": "feedback"
    },
    {
        "id": "default-navigation-HamburgerMenu",
        "label": "HamburgerMenu",
        "files": [
            "sections/default/navigation/HamburgerMenu"
        ],
        "dependencies": [],
        "group": "default",
        "category": "navigation"
    },
    {
        "id": "keystone-CustomFields-DynamicStatusLabel",
        "label": "DynamicStatusLabel",
        "files": [
            "sections/keystone/CustomFields/DynamicStatusLabel"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-EquasionTextArea",
        "label": "EquasionTextArea",
        "files": [
            "sections/keystone/CustomFields/EquasionTextArea"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-HiddenInput",
        "label": "HiddenInput",
        "files": [
            "sections/keystone/CustomFields/HiddenInput"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-Integer",
        "label": "Integer",
        "files": [
            "sections/keystone/CustomFields/Integer"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-LongText",
        "label": "LongText",
        "files": [
            "sections/keystone/CustomFields/LongText"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-Relationship",
        "label": "Relationship",
        "files": [
            "sections/keystone/CustomFields/Relationship"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-RelationshipMany",
        "label": "RelationshipMany",
        "files": [
            "sections/keystone/CustomFields/RelationshipMany"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-Text",
        "label": "Text",
        "files": [
            "sections/keystone/CustomFields/Text"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-TimeNotUTC",
        "label": "TimeNotUTC",
        "files": [
            "sections/keystone/CustomFields/TimeNotUTC"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-TimeZone",
        "label": "TimeZone",
        "files": [
            "sections/keystone/CustomFields/TimeZone"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-CustomFields-Title",
        "label": "Title",
        "files": [
            "sections/keystone/CustomFields/Title"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "CustomFields"
    },
    {
        "id": "keystone-data-display-ItemsList",
        "label": "ItemsList",
        "files": [
            "sections/keystone/data-display/ItemsList"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "data-display"
    },
    {
        "id": "keystone-feedback-NotFoundSection",
        "label": "NotFoundSection",
        "files": [
            "sections/keystone/feedback/NotFoundSection"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "feedback"
    },
    {
        "id": "keystone-forms-ActionButtons",
        "label": "ActionButtons",
        "files": [
            "sections/keystone/forms/ActionButtons"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-ButtonGroup",
        "label": "ButtonGroup",
        "files": [
            "sections/keystone/forms/ButtonGroup"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-CreateItemForm",
        "label": "CreateItemForm",
        "files": [
            "sections/keystone/forms/CreateItemForm"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-DynamicForms",
        "label": "DynamicForms",
        "files": [
            "sections/keystone/forms/DynamicForms"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-EditItemForm",
        "label": "EditItemForm",
        "files": [
            "sections/keystone/forms/EditItemForm"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-forms-SignInContainer",
        "label": "SignInContainer",
        "files": [
            "sections/keystone/forms/SignInContainer"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "forms"
    },
    {
        "id": "keystone-layout-PageContainer",
        "label": "PageContainer",
        "files": [
            "sections/keystone/layout/PageContainer"
        ],
        "dependencies": [],
        "group": "keystone",
        "category": "layout"
    }
];
