// -------------------------------------------------------------------------
// 🛑 THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
// -------------------------------------------------------------------------
// Run 'npm run generate:registry' (or build) to update.
    
export interface ComponentDef {
    id: string;
    label: string;
    files: string[];
    dependencies: string[];
    group: string; // 'default', 'keystone', 'textures'
}

export const GENERATED_COMPONENTS: ComponentDef[] = [
    {
        "id": "Cloud",
        "label": "Texture: Cloud",
        "files": [
            "components/textures/Cloud"
        ],
        "dependencies": [],
        "group": "textures"
    },
    {
        "id": "common",
        "label": "common",
        "files": [
            "components/default/common"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "common",
        "label": "Keystone: common",
        "files": [
            "components/keystone/common"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "data-display",
        "label": "data-display",
        "files": [
            "components/default/data-display"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "data-display",
        "label": "Keystone: data-display",
        "files": [
            "components/keystone/data-display"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "feedback",
        "label": "feedback",
        "files": [
            "components/default/feedback"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "feedback",
        "label": "Keystone: feedback",
        "files": [
            "components/keystone/feedback"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "forms",
        "label": "forms",
        "files": [
            "components/default/forms"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "forms",
        "label": "Keystone: forms",
        "files": [
            "components/keystone/forms"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "layout",
        "label": "layout",
        "files": [
            "components/default/layout"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "navigation",
        "label": "navigation",
        "files": [
            "components/default/navigation"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "navigation",
        "label": "Keystone: navigation",
        "files": [
            "components/keystone/navigation"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "overlays",
        "label": "overlays",
        "files": [
            "components/default/overlays"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "overlays",
        "label": "Keystone: overlays",
        "files": [
            "components/keystone/overlays"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "Paper",
        "label": "Texture: Paper",
        "files": [
            "components/textures/Paper"
        ],
        "dependencies": [],
        "group": "textures"
    }
];

export const GENERATED_SECTIONS: ComponentDef[] = [
    {
        "id": "common",
        "label": "Keystone: common",
        "files": [
            "sections/keystone/common"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "CustomFields",
        "label": "Keystone: CustomFields",
        "files": [
            "sections/keystone/CustomFields"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "data-display",
        "label": "Keystone: data-display",
        "files": [
            "sections/keystone/data-display"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "feedback",
        "label": "feedback",
        "files": [
            "sections/default/feedback"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "feedback",
        "label": "Keystone: feedback",
        "files": [
            "sections/keystone/feedback"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "forms",
        "label": "Keystone: forms",
        "files": [
            "sections/keystone/forms"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "layout",
        "label": "Keystone: layout",
        "files": [
            "sections/keystone/layout"
        ],
        "dependencies": [],
        "group": "keystone"
    },
    {
        "id": "navigation",
        "label": "navigation",
        "files": [
            "sections/default/navigation"
        ],
        "dependencies": [],
        "group": "default"
    },
    {
        "id": "overlays",
        "label": "Keystone: overlays",
        "files": [
            "sections/keystone/overlays"
        ],
        "dependencies": [],
        "group": "keystone"
    }
];
