import * as fs from 'fs-extra';
import * as path from 'path';

// --- CONFIGURATION ---

const CLI_PKG_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(CLI_PKG_ROOT, '../../');
const COMPONENTS_DIR = path.join(REPO_ROOT, 'packages/components');
const SECTIONS_DIR = path.join(REPO_ROOT, 'packages/sections');

const OUTPUT_FILE = path.join(CLI_PKG_ROOT, 'src/config/registry.generated.ts');

// Manual overrides for things we can't easily auto-detect
const OVERRIDES: Record<string, { label?: string, dependencies?: string[] }> = {
    // Default Components
    'Charts': { label: 'Charts (Recharts)', dependencies: ['recharts', 'd3-scale'] },
    'HtmlEditor': { label: 'Rich Text Editor', dependencies: ['@tiptap/react', '@tiptap/starter-kit'] },
    'Loading': { label: 'Loading Indicators' }, // Note: Original had multiple files for Loading, but folder structure might differ now.
    // If "Loading", "LoadingSpinner", "Spinner" are separate folders, they will be separate components now.
    // If they were merged in the manual list, we need to decide if we keep them separate or not.
    // Use manual exclusion if needed.

    // Keystone
    'KeystoneModals': { label: 'Keystone: Modals' },
};

// Exclude these directories from being registered as components
const EXCLUDES = ['.DS_Store', 'utils', 'styles.ts', 'index.ts', 'index.tsx'];

interface ComponentDef {
    id: string;
    label: string;
    files: string[];
    dependencies: string[];
    group: string;
}

// --- GENERATOR ---

async function generate() {
    console.log('🔄 Generating Component Registry...');

    const components = await scanDirectory(COMPONENTS_DIR, 'components');
    const sections = await scanDirectory(SECTIONS_DIR, 'sections');

    const content = `// -------------------------------------------------------------------------
// 🛑 THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
// -------------------------------------------------------------------------
// Run 'npm run generate:registry' (or build) to update.
    
export interface ComponentDef {
    id: string;
    label: string;
    files: string[];
    dependencies: string[];
    group: string; // 'default', 'keystone', 'textures'
}

export const GENERATED_COMPONENTS: ComponentDef[] = ${JSON.stringify(components, null, 4)};

export const GENERATED_SECTIONS: ComponentDef[] = ${JSON.stringify(sections, null, 4)};
`;

    await fs.writeFile(OUTPUT_FILE, content);
    console.log(`✅ Registry written to ${OUTPUT_FILE}`);
}

async function scanDirectory(baseDir: string, type: 'components' | 'sections'): Promise<ComponentDef[]> {
    const results: ComponentDef[] = [];

    if (!await fs.pathExists(baseDir)) return [];

    const groups = await fs.readdir(baseDir);

    for (const group of groups) {
        if (EXCLUDES.includes(group)) continue;
        const groupDir = path.join(baseDir, group);
        if (!(await fs.stat(groupDir)).isDirectory()) continue;

        const items = await fs.readdir(groupDir);
        for (const item of items) {
            if (EXCLUDES.includes(item)) continue;

            const itemPath = path.join(groupDir, item);
            if (!(await fs.stat(itemPath)).isDirectory()) {
                // It's a file at the group level (e.g. index.ts), ignore.
                continue;
            }

            // ID is the folder name
            const id = item;

            // Check overrides
            const override = OVERRIDES[id] || {};

            // Label: Use override or default to ID
            let label = override.label || id;

            // Prefix Keystone components (optional, matches current behavior)
            if (group === 'keystone' && !label.startsWith('Keystone:')) {
                label = `Keystone: ${label}`;
            }
            if (group === 'textures' && !label.startsWith('Texture:')) {
                label = `Texture: ${label}`;
            }

            const def: ComponentDef = {
                id: id,
                label: label,
                files: [`${type}/${group}/${id}`],
                dependencies: override.dependencies || [],
                group: group
            };

            results.push(def);
        }
    }

    // Sort by ID for stability
    return results.sort((a, b) => a.id.localeCompare(b.id));
}

generate().catch(console.error);
